import { useMemo } from 'react'
import { createClient } from '../client'
import { getSdkWithHooks } from '../generated/sdk.autogenKey'

const REPO_A = 'octocat/example-repo-2'
const REPO_B = 'octocat/example-repo-3'

export function CustomKeyDemo() {
  const sdk = useMemo(() => getSdkWithHooks(createClient()), [])

  // Extend: same variables, but each widget appends its own namespace to the
  // autogenerated key, so they get independent SWR caches.
  const widgetA = sdk.useComment({ repoFullName: REPO_A }, undefined, (key) => [...(key as unknown[]), 'widget-a'])
  const widgetB = sdk.useComment({ repoFullName: REPO_A }, undefined, (key) => [...(key as unknown[]), 'widget-b'])

  // Override: different variables, but both are forced onto the same custom
  // key, so they share a single SWR cache entry.
  const sharedX = sdk.useComment({ repoFullName: REPO_A }, undefined, () => ['SharedComment'])
  const sharedY = sdk.useComment({ repoFullName: REPO_B }, undefined, () => ['SharedComment'])

  return (
    <section className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-slate-900">overrideKey: extend the autogenerated key</h2>
        <p className="text-sm text-slate-500">
          Both widgets call <code>useComment</code> with identical variables, but each appends a different
          namespace to the key. Revalidating one does not affect the other.
        </p>
        <div className="mt-3 grid grid-cols-2 gap-4">
          {[
            { label: 'widget-a', result: widgetA },
            { label: 'widget-b', result: widgetB },
          ].map(({ label, result }) => (
            <div key={label} className="rounded border border-slate-200 p-4">
              <div className="mb-2 flex items-center justify-between">
                <p className="font-medium">{label}</p>
                <button
                  type="button"
                  onClick={() => result.mutate()}
                  className="rounded bg-slate-800 px-2 py-1 text-xs text-white hover:bg-slate-700"
                >
                  Revalidate
                </button>
              </div>
              {result.isLoading && <p className="text-slate-500">loading...</p>}
              {result.data?.entry && (
                <p className="text-sm text-slate-600">comments: {result.data.entry.commentCount}</p>
              )}
            </div>
          ))}
        </div>
      </div>

      <div>
        <h2 className="text-lg font-semibold text-slate-900">overrideKey: override the autogenerated key</h2>
        <p className="text-sm text-slate-500">
          These two widgets query <em>different</em> repositories, but both force the key to{' '}
          <code>['SharedComment']</code>, so SWR treats them as the same cache entry: revalidating either one
          updates both.
        </p>
        <div className="mt-3 grid grid-cols-2 gap-4">
          {[
            { label: REPO_A, result: sharedX },
            { label: REPO_B, result: sharedY },
          ].map(({ label, result }) => (
            <div key={label} className="rounded border border-slate-200 p-4">
              <div className="mb-2 flex items-center justify-between">
                <p className="font-medium">{label}</p>
                <button
                  type="button"
                  onClick={() => result.mutate()}
                  className="rounded bg-slate-800 px-2 py-1 text-xs text-white hover:bg-slate-700"
                >
                  Revalidate
                </button>
              </div>
              {result.isLoading && <p className="text-slate-500">loading...</p>}
              {result.data?.entry && (
                <p className="text-sm text-slate-600">
                  {result.data.entry.repository.full_name} - comments: {result.data.entry.commentCount}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
