name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.node-version == '26' }}

    strategy:
      matrix:
        node-version: ['22', '24', '26']

    steps:
      - uses: actions/checkout@v3
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, and test
        run: |
          yarn install --pure-lockfile
          yarn test
        env:
          CI: true
